name: food_delivery_admin
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Common
  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.14
  flutter_staggered_grid_view: ^0.6.1
  http: ^0.13.4
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  intl:
  syncfusion_flutter_charts:
  permission_handler:
  permission_handler_web: ^0.0.2
  # Firebase
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth:
  google_fonts: ^2.3.1
  firebase_storage: ^10.2.9
  paginate_firestore: ^1.0.3

  # Vector Icons
  flutter_vector_icons: ^1.0.0

  # Cache Image
  cached_network_image: ^3.2.0

  # One Signal Push notification
  onesignal_flutter: ^3.3.0
  flutter_colorpicker: ^1.0.3

  # others
  url_strategy: ^0.2.0
  js: ^0.6.3

  #charts
  fl_chart: ^0.46.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/flag/
    - lang/
